"""
harmonicai/scripts/generate_synthetic_data.py

Phase 0 — Synthetic Dataset Generator
=====================================
Generates structurally valid, statistically plausible synthetic datasets for:
  1. tracks.csv       — Audio feature vectors for 5,000 tracks
  2. users.csv        — User baseline profiles for 500 users
  3. sessions.csv     — Session feedback events (weak-labelled)

Design Principles:
  - Features sampled from empirically validated distributions (not uniform random)
  - Labels generated by a documented oracle function (not a black box)
  - Controlled Gaussian noise (σ=0.15) on self-reported fields
  - All distributions are seeded for reproducibility

Run:
    python scripts/generate_synthetic_data.py
"""

import numpy as np
import pandas as pd
import uuid
import json
from pathlib import Path
from dataclasses import dataclass, field
from typing import List, Tuple

# ─────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────

SEED = 42
N_TRACKS = 5_000
N_USERS  = 500
N_SESSIONS = 8_000   # ~16 sessions per user on average

OUTPUT_DIR = Path(__file__).parent.parent / "data" / "synthetic"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

rng = np.random.default_rng(SEED)


# ─────────────────────────────────────────────
# PART 1: Track Generation
# ─────────────────────────────────────────────
# Each feature is sampled from a distribution that mirrors
# the actual Spotify track catalogue statistics.
# Source: Spotify Million Song Dataset EDA (public Kaggle studies).

def generate_tracks(n: int) -> pd.DataFrame:
    """
    Generate n synthetic audio tracks with realistic feature distributions.

    Why these distributions?
    - tempo_bpm: Real tracks cluster around 90–130 BPM (pop/rock dominance)
      but therapeutic tracks skew lower → we use a bimodal mix.
    - valence/energy: Beta distributions (α<β) → most real tracks are moderate,
      not extreme. Uniform would be unrealistic.
    - instrumentalness: Highly skewed right; most tracks have vocals.
    """

    # Tempo: bimodal — chill cluster (55–85) + mainstream cluster (100–140)
    tempo_chill      = rng.normal(loc=68,  scale=8,  size=n // 3).clip(40, 90)
    tempo_mainstream = rng.normal(loc=118, scale=15, size=n - n // 3).clip(80, 200)
    tempo_bpm        = rng.permutation(np.concatenate([tempo_chill, tempo_mainstream]))

    # Beta(α, β): skewed distributions for perceptual features
    valence          = rng.beta(a=2.5, b=2.5, size=n)          # roughly symmetric
    energy           = rng.beta(a=3.0, b=2.0, size=n)          # skewed toward higher energy
    acousticness     = rng.beta(a=1.5, b=4.0, size=n)          # most tracks non-acoustic
    danceability     = rng.beta(a=3.0, b=2.5, size=n)          # skewed toward danceable
    instrumentalness = rng.beta(a=0.5, b=5.0, size=n).clip(0, 1)  # heavy right-skew
    speechiness      = rng.beta(a=0.8, b=6.0, size=n).clip(0, 1)  # most tracks: no speech

    # Loudness: real tracks cluster around -7 to -5 dB (mastered)
    loudness_db      = rng.normal(loc=-9.0, scale=5.0, size=n).clip(-60, 0)

    # Discrete features
    key              = rng.integers(0, 12, size=n)
    mode             = rng.choice([0, 1], size=n, p=[0.40, 0.60])  # 60% major
    time_signature   = rng.choice([3, 4, 5, 6], size=n, p=[0.10, 0.82, 0.05, 0.03])

    # Duration: 2–6 minutes for most tracks
    duration_ms      = rng.normal(loc=210_000, scale=50_000, size=n).clip(30_000, 600_000)

    df = pd.DataFrame({
        "track_id":         [f"synth:track:{uuid.uuid4()}" for _ in range(n)],
        "tempo_bpm":        tempo_bpm.round(2),
        "valence":          valence.round(4),
        "energy":           energy.round(4),
        "acousticness":     acousticness.round(4),
        "instrumentalness": instrumentalness.round(4),
        "danceability":     danceability.round(4),
        "speechiness":      speechiness.round(4),
        "loudness_db":      loudness_db.round(2),
        "key":              key,
        "mode":             mode,
        "time_signature":   time_signature,
        "duration_ms":      duration_ms.astype(int),
    })

    return df


# ─────────────────────────────────────────────
# PART 2: User Profile Generation
# ─────────────────────────────────────────────

INTENTS = ["anxiety_relief", "sleep_induction", "deep_focus", "mood_uplift", "grief_processing"]
AGE_BANDS = ["18-24", "25-34", "35-44", "45-54", "55+"]
INTENT_WEIGHTS = [0.35, 0.25, 0.20, 0.15, 0.05]  # anxiety most common in B2C

def generate_users(n: int) -> pd.DataFrame:
    """
    Generate user baseline profiles.
    
    Key design choice: baseline_mood is sampled from a left-skewed distribution
    because our app attracts users who are already struggling — they don't onboard
    when they feel great. This is selection bias we must account for in Phase 1.
    """
    baseline_mood = rng.beta(a=2.0, b=4.0, size=n) * 100  # left-skewed toward lower moods
    
    df = pd.DataFrame({
        "user_id":        [str(uuid.uuid4()) for _ in range(n)],
        "age_band":       rng.choice(AGE_BANDS, size=n, p=[0.22, 0.35, 0.25, 0.12, 0.06]),
        "primary_intent": rng.choice(INTENTS, size=n, p=INTENT_WEIGHTS),
        "baseline_mood":  baseline_mood.round(1).clip(0, 100),
        "has_sensitivity_flag": rng.choice([True, False], size=n, p=[0.15, 0.85]),
    })

    return df


# ─────────────────────────────────────────────
# PART 3: Oracle Label Function
# ─────────────────────────────────────────────
# IMPORTANT: This function is the documented "ground truth" for our synthetic data.
# In production, labels come from real user feedback.
# During development, we use this oracle so we always know what accuracy is
# theoretically achievable (upper bound for model evaluation).

def oracle_efficacy(track: pd.Series, intent: str, noise_std: float = 0.15) -> Tuple[float, int]:
    """
    Deterministic rule-based oracle that mimics the weak-label priors from the
    psychoacoustic literature (see configs/feature_schema.yaml: weak_label_rules).
    
    Returns:
        (raw_score, label)  where label ∈ {-1, 0, +1}
    
    The noise_std parameter injects Gaussian noise to simulate self-report error.
    Without noise: we'd have a perfect oracle → unrealistic and would make models
    overfit to this function.
    """

    score = 0.0  # accumulate a raw therapeutic fit score

    if intent == "anxiety_relief":
        # Penalize high energy heavily (cortisol risk)
        score += 1.0 if 60 <= track["tempo_bpm"] <= 80 else -0.5
        score += 1.0 if track["energy"] < 0.4 else -0.8
        score += 0.5 if track["acousticness"] > 0.5 else 0.0
        score += 0.5 if track["instrumentalness"] > 0.6 else 0.0
        score += 0.3 if track["loudness_db"] > -30 else -0.3

    elif intent == "sleep_induction":
        score += 1.2 if track["tempo_bpm"] < 65 else -0.8
        score += 1.0 if track["energy"] < 0.3 else -1.0
        score += 0.5 if track["instrumentalness"] > 0.7 else -0.2
        score += 0.3 if 0.2 <= track["valence"] <= 0.6 else 0.0

    elif intent == "deep_focus":
        # Bimodal tempo: either very slow or fast (no lyrics)
        in_focus_range = (40 <= track["tempo_bpm"] <= 60) or (120 <= track["tempo_bpm"] <= 140)
        score += 1.0 if in_focus_range else -0.5
        score += 0.8 if track["speechiness"] < 0.1 else -1.0
        score += 0.4 if 0.3 <= track["energy"] <= 0.6 else 0.0

    elif intent == "mood_uplift":
        score += 1.0 if track["valence"] > 0.65 else -0.5
        score += 0.8 if 0.5 <= track["energy"] <= 0.8 else 0.0
        score += 0.5 if track["mode"] == 1 else 0.0  # major key

    elif intent == "grief_processing":
        # Counter-intuitive: lower valence, slower tempo can validate grief
        score += 0.8 if track["tempo_bpm"] < 80 else 0.0
        score += 0.6 if track["valence"] < 0.5 else -0.3
        score += 0.5 if track["acousticness"] > 0.5 else 0.0

    # Add self-report noise
    noise = rng.normal(0, noise_std)
    score += noise

    # Map to label
    if score >= 1.5:
        label = 1
    elif score <= 0.2:
        label = -1
    else:
        label = 0

    return round(score, 4), label


# ─────────────────────────────────────────────
# PART 4: Session Feedback Generation
# ─────────────────────────────────────────────

def generate_sessions(users: pd.DataFrame, tracks: pd.DataFrame, n: int) -> pd.DataFrame:
    """
    Simulate n therapy sessions by:
    1. Sampling a random (user, track) pair
    2. Computing oracle efficacy for the user's primary intent
    3. Deriving mood_pre, mood_post, and efficacy_rating from the oracle score
    
    The mood values have additional noise layered on to simulate:
    - Regression to the mean (users report smaller changes than they experience)
    - Response bias (tendency to rate positively due to social desirability)
    """

    user_sample  = users.sample(n=n, replace=True, random_state=SEED).reset_index(drop=True)
    track_sample = tracks.sample(n=n, replace=True, random_state=SEED+1).reset_index(drop=True)

    records = []
    for i in range(n):
        user  = user_sample.iloc[i]
        track = track_sample.iloc[i]
        intent = user["primary_intent"]

        raw_score, label = oracle_efficacy(track, intent)

        # Simulate mood_pre: drawn from user's baseline with session-level noise
        mood_pre = float(user["baseline_mood"]) + rng.normal(0, 8)
        mood_pre = np.clip(mood_pre, 0, 100)

        # Simulate mood_post based on oracle label
        delta_map = {1: rng.uniform(6, 20), 0: rng.uniform(-4, 5), -1: rng.uniform(-20, -6)}
        mood_post = np.clip(mood_pre + delta_map[label], 0, 100)

        # Simulate explicit efficacy rating (1–10) with positive bias noise
        base_rating = {1: 8.0, 0: 5.0, -1: 2.5}[label]
        efficacy_rating = int(np.clip(rng.normal(base_rating, 1.2), 1, 10))

        # Skip probability: higher for harmful tracks
        skipped = rng.random() < (0.05 if label == 1 else 0.15 if label == 0 else 0.45)

        records.append({
            "session_id":      str(uuid.uuid4()),
            "user_id":         user["user_id"],
            "track_id":        track["track_id"],
            "session_intent":  intent,
            "mood_pre":        round(mood_pre, 1),
            "mood_post":       round(float(mood_post), 1),
            "efficacy_rating": efficacy_rating,
            "completed":       not skipped,
            "oracle_score":    raw_score,    # kept for Phase 0 validation only
            "efficacy_label":  label,        # derived label: target variable
        })

    return pd.DataFrame(records)


# ─────────────────────────────────────────────
# PART 5: Validation Checks
# ─────────────────────────────────────────────

def validate_dataset(tracks: pd.DataFrame, users: pd.DataFrame, sessions: pd.DataFrame):
    """
    Structural and statistical validation.
    These checks would live in a CI pipeline in production.
    """
    errors = []

    # Schema completeness
    assert not tracks.isnull().any().any(),     "FAIL: tracks has null values"
    assert not users.isnull().any().any(),      "FAIL: users has null values"
    assert not sessions.isnull().any().any(),   "FAIL: sessions has null values"

    # Range checks
    assert tracks["tempo_bpm"].between(40, 220).all(),    "FAIL: tempo out of range"
    assert tracks["valence"].between(0, 1).all(),          "FAIL: valence out of range"
    assert tracks["energy"].between(0, 1).all(),           "FAIL: energy out of range"
    assert users["baseline_mood"].between(0, 100).all(),   "FAIL: baseline_mood out of range"
    assert sessions["mood_pre"].between(0, 100).all(),     "FAIL: mood_pre out of range"
    assert sessions["mood_post"].between(0, 100).all(),    "FAIL: mood_post out of range"
    assert sessions["efficacy_rating"].between(1, 10).all(),"FAIL: efficacy_rating out of range"

    # Label distribution (check for severe imbalance)
    label_dist = sessions["efficacy_label"].value_counts(normalize=True)
    for label_val, proportion in label_dist.items():
        if proportion < 0.10:
            errors.append(f"WARNING: Label {label_val} is only {proportion:.1%} of data — severe imbalance")

    print("\n✅ Validation passed")
    print(f"   Tracks:   {len(tracks):,} rows, {tracks.shape[1]} features")
    print(f"   Users:    {len(users):,} rows, {users.shape[1]} features")
    print(f"   Sessions: {len(sessions):,} rows, {sessions.shape[1]} features")
    print(f"\n📊 Label distribution (efficacy_label):")
    for k, v in label_dist.items():
        bar = "█" * int(v * 40)
        print(f"   {k:+d} | {bar:<40} {v:.1%}")

    if errors:
        print("\n⚠️  Warnings:")
        for e in errors:
            print(f"   {e}")

    return True


# ─────────────────────────────────────────────
# PART 6: Feature Summary (for Phase 1 preview)
# ─────────────────────────────────────────────

def print_feature_summary(tracks: pd.DataFrame):
    print("\n📐 Track Feature Summary Statistics:")
    numeric_cols = ["tempo_bpm", "valence", "energy", "acousticness",
                    "instrumentalness", "danceability", "speechiness", "loudness_db"]
    summary = tracks[numeric_cols].describe().round(3)
    print(summary.to_string())

    print("\n🔔 Notable distribution insights:")
    print(f"   Tracks with instrumentalness > 0.5: {(tracks['instrumentalness'] > 0.5).mean():.1%}")
    print(f"   Tracks with speechiness > 0.33:    {(tracks['speechiness'] > 0.33).mean():.1%}")
    print(f"   Tracks in major key (mode=1):       {(tracks['mode'] == 1).mean():.1%}")
    print(f"   Tracks in 4/4 time:                 {(tracks['time_signature'] == 4).mean():.1%}")


# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 60)
    print("  HarmonicAI — Phase 0: Synthetic Dataset Generator")
    print("=" * 60)

    print("\n[1/4] Generating track features...")
    tracks = generate_tracks(N_TRACKS)

    print("[2/4] Generating user profiles...")
    users = generate_users(N_USERS)

    print("[3/4] Generating session feedback events...")
    sessions = generate_sessions(users, tracks, N_SESSIONS)

    print("[4/4] Validating datasets...")
    validate_dataset(tracks, users, sessions)

    print_feature_summary(tracks)

    # Persist to CSV (parquet preferred in production; CSV for Phase 0 portability)
    tracks.to_csv(OUTPUT_DIR / "tracks.csv", index=False)
    users.to_csv(OUTPUT_DIR / "users.csv", index=False)
    sessions.to_csv(OUTPUT_DIR / "sessions.csv", index=False)

    # Save data manifest for reproducibility
    manifest = {
        "phase": 0,
        "seed": SEED,
        "n_tracks": N_TRACKS,
        "n_users": N_USERS,
        "n_sessions": N_SESSIONS,
        "noise_std": 0.15,
        "files": {
            "tracks":   "data/synthetic/tracks.csv",
            "users":    "data/synthetic/users.csv",
            "sessions": "data/synthetic/sessions.csv",
        }
    }
    with open(OUTPUT_DIR / "manifest.json", "w") as f:
        json.dump(manifest, f, indent=2)

    print(f"\n✅ Datasets saved to: {OUTPUT_DIR}")
    print(f"   Manifest:          {OUTPUT_DIR}/manifest.json")
    print("\nNext step → Phase 1: python src/ingestion/profiler.py\n")
